### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by webkonglong** [wangbin/jiebago#11]
```
package main

import (
	"log"

	"github.com/wangbin/jiebago"
)
var seg jiebago.Segmenter
func main() {
	log.Println(seg.CutAll("我来到北京清华大学"))
}
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x28 pc=0x4bcf13]

goroutine 4 [running]:
sync.(*RWMutex).RLock(...)
        C:/Go/src/sync/rwmutex.go:48
github.com/wangbin/jiebago.(*Dictionary).Frequency(0x0, 0xc0001c5dd8, 0x3, 0x20, 0xc0001c5dd8)
        C:/Users/amz/Desktop/gotest/src/github.com/wangbin/jiebago/dictionary.go:54 +0x33
github.com/wangbin/jiebago.(*Segmenter).dag(0x625688, 0xc0001c5ea0, 0x9, 0x20, 0x9)
        C:/Users/amz/Desktop/gotest/src/github.com/wangbin/jiebago/jieba.go:118 +0xbe
github.com/wangbin/jiebago.(*Segmenter).cutAll.func1(0x4fe190, 0x1b, 0x625688, 0xc000010060)
        C:/Users/amz/Desktop/gotest/src/github.com/wangbin/jiebago/jieba.go:303 +0x9d
created by github.com/wangbin/jiebago.(*Segmenter).cutAll
        C:/Users/amz/Desktop/gotest/src/github.com/wangbin/jiebago/jieba.go:301 +0x86
exit status 
```

**Comment by leexuehan** [comment]
> ```
> package main
> 
> import (
> 	"log"
> 
> 	"github.com/wangbin/jiebago"
> )
> var seg jiebago.Segmenter
> func main() {
> 	log.Println(seg.CutAll("我来到北京清华大学"))
> }
> ```
> 
> ```
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xc0000005 code=0x1 addr=0x28 pc=0x4bcf13]
> 
> goroutine 4 [running]:
> sync.(*RWMutex).RLock(...)
>         C:/Go/src/sync/rwmutex.go:48
> github.com/wangbin/jiebago.(*Dictionary).Frequency(0x0, 0xc0001c5dd8, 0x3, 0x20, 0xc0001c5dd8)
>         C:/Users/amz/Desktop/gotest/src/github.com/wangbin/jiebago/dictionary.go:54 +0x33
> github.com/wangbin/jiebago.(*Segmenter).dag(0x625688, 0xc0001c5ea0, 0x9, 0x20, 0x9)
>         C:/Users/amz/Desktop/gotest/src/github.com/wangbin/jiebago/jieba.go:118 +0xbe
> github.com/wangbin/jiebago.(*Segmenter).cutAll.func1(0x4fe190, 0x1b, 0x625688, 0xc000010060)
>         C:/Users/amz/Desktop/gotest/src/github.com/wangbin/jiebago/jieba.go:303 +0x9d
> created by github.com/wangbin/jiebago.(*Segmenter).cutAll
>         C:/Users/amz/Desktop/gotest/src/github.com/wangbin/jiebago/jieba.go:301 +0x86
> exit status 
> ```

Maybe you need to load dictionary to init seg first.
